// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	entity "github.com/SchunckLeonardo/library-management-system/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// BookRepositoryInterface is an autogenerated mock type for the BookRepositoryInterface type
type BookRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: book
func (_m *BookRepositoryInterface) Create(book entity.Book) error {
	ret := _m.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Book) error); ok {
		r0 = rf(book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *BookRepositoryInterface) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: id
func (_m *BookRepositoryInterface) GetById(id string) (entity.Book, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.Book, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entity.Book); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Book)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with no fields
func (_m *BookRepositoryInterface) ListAll() ([]entity.Book, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []entity.Book
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Book, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Book)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: book
func (_m *BookRepositoryInterface) Update(book entity.Book) error {
	ret := _m.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Book) error); ok {
		r0 = rf(book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookRepositoryInterface creates a new instance of BookRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepositoryInterface {
	mock := &BookRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
